### ISSUE TITLE
Chef fails during first run

### ISSUE THREAD

**Issue by obersoldat** [bipinbachhao/ssh_auth_keys#1]
Hi,
I have a really weird issue with this cookbook. Its setup this way. On my local git there is a recipe that runs this recipe, and in attributes it is specified for which user auth keys should be added. It has worked for a long time for root user, but now I need to add them for another user. No matter either I specify it via attributes or via environment file, it will fail on first chef run during provisioning. But if I run it manually afterwards, it will work. Chef: 14.0.202

> [2018-05-18T11:03:21+00:00] INFO: Processing linux_user[root] action modify (change_user_password::default line 17)
> [2018-05-18T11:03:21+00:00] INFO: linux_user[root] modified
> [2018-05-18T11:03:21+00:00] INFO: Processing linux_user[rundeck] action create (localusers::rundeck line 6)
> [2018-05-18T11:03:21+00:00] INFO: linux_user[rundeck] created
> [2018-05-18T11:03:21+00:00] INFO: Processing ruby_block[ssh_auth_keys_copying] action run (ssh_auth_keys::default line 10)
> [2018-05-18T11:03:21+00:00] INFO: Keep authorized old keys entries from: /root/.ssh/authorized_keys 
> [2018-05-18T11:03:21+00:00] INFO: Processing template[Creating_authorized_keys_file] action create (dynamically defined)
> [2018-05-18T11:03:21+00:00] INFO: template[Creating_authorized_keys_file] backed up to /var/chef/backup/root/.ssh/authorized_keys.chef-20180518110321.708441
> [2018-05-18T11:03:21+00:00] INFO: template[Creating_authorized_keys_file] updated file contents /root/.ssh/authorized_keys
> [2018-05-18T11:03:21+00:00] INFO: Running queued delayed notifications before re-raising exception
> [2018-05-18T11:03:21+00:00] ERROR: Running exception handlers
> [2018-05-18T11:03:21+00:00] ERROR: Exception handlers complete
> [2018-05-18T11:03:21+00:00] INFO: Sending resource update report (run-id: c0c76e0b-e600-4b47-8c66-e73e493c4fa1)
> [2018-05-18T11:03:22+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
> [2018-05-18T11:03:22+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
> [2018-05-18T11:03:22+00:00] FATAL: NoMethodError: ruby_block[ssh_auth_keys_copying] (ssh_auth_keys::default line 10) had an error: NoMethodError: undefined method `gid' for Chef::Resource::RubyBlock

> # cat /var/chef/cache/chef-stacktrace.out
> Generated at 2018-05-18 11:03:22 +0000
> NoMethodError: ruby_block[ssh_auth_keys_copying] (ssh_auth_keys::default line 10) had an error: NoMethodError: undefined method `gid' for Chef::Resource::RubyBlock
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource.rb:1286:in `method_missing'
> /var/chef/cache/cookbooks/ssh_auth_keys/recipes/default.rb:31:in `block (3 levels) in from_file'
> /var/chef/cache/cookbooks/ssh_auth_keys/recipes/default.rb:13:in `each'
> /var/chef/cache/cookbooks/ssh_auth_keys/recipes/default.rb:13:in `block (2 levels) in from_file'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/ruby_block.rb:31:in `block in action_run'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/mixin/why_run.rb:51:in `add_action'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:227:in `converge_by'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/ruby_block.rb:30:in `action_run'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:182:in `run_action'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource.rb:576:in `run_action'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:70:in `run_action'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block (2 levels) in converge'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `each'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block in converge'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:97:in `converge'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:717:in `block in converge'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `catch'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `converge'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:751:in converge_and_save'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:283:in `run'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:303:in run_with_graceful_exit_option'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:279:in `block in run_chef_client'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/local_mode.rb:44:in with_server_connectivity'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:261:in run_chef_client'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/client.rb:440:in run_application'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:66:in `run'
> /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/bin/chef-client:26:in `<top (required)>'
> /usr/bin/chef-client:59:in `load'
> /usr/bin/chef-client:59:in `<main>'

The best guess is that single quotes are missing in recipe on this line:
`user = { 'uid' => target_user, gid => target_user, 'dir' => "/home/#{target_user}" } unless user`

**Comment by obersoldat** [comment]
Found a solution for the issue. As mentioned in my original post on the end, single quotes are missing.
This line needed to be changed to:
`user = { 'uid' => target_user, 'gid' => target_user, 'dir' => "/home/#{target_user}" } unless user`

I've cloned the cookbook to my local repo, changed the code and works now like a charm.

**Comment by bipinbachhao** [comment]
Fixed Issue #1 uploaded update cookbook to Supermarket.
